package req

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io"
	"regexp"
	"strconv"
	"strings"
	"time"
)

var ErrInvalidDelim = errors.New("req: invalid delim")
var ErrInvalidToken = errors.New("req: invalid token")

var patternAllNumber = regexp.MustCompile(`^\d+$`)
var pattern2 = regexp.MustCompile(`(^|[^a-zA-Z])([a-z]+)`)
var pattern3 = regexp.MustCompile(`([A-Z])([a-z]+)`)
var pattern4 = regexp.MustCompile(`[^a-zA-Z0-9]`)

var numbers = map[byte]string{
	'0': "Zero_",
	'1': "One_",
	'2': "Two_",
	'3': "Three_",
	'4': "Four_",
	'5': "Five_",
	'6': "Six_",
	'7': "Seven_",
	'8': "Eight_",
	'9': "Nine_",
}

var Void = struct{}{}

var Abbreviation = map[string]struct{}{
	"API":   Void,
	"ASCII": Void,
	"CPU":   Void,
	"CSS":   Void,
	"DNS":   Void,
	"EOF":   Void,
	"GUID":  Void,
	"HTML":  Void,
	"HTTP":  Void,
	"HTTPS": Void,
	"ID":    Void,
	"IP":    Void,
	"JSON":  Void,
	"LHS":   Void,
	"QPS":   Void,
	"RAM":   Void,
	"RHS":   Void,
	"RPC":   Void,
	"SLA":   Void,
	"SMTP":  Void,
	"SSH":   Void,
	"TCP":   Void,
	"TLS":   Void,
	"TTL":   Void,
	"UDP":   Void,
	"UI":    Void,
	"UID":   Void,
	"UUID":  Void,
	"URI":   Void,
	"URL":   Void,
	"UTF8":  Void,
	"VM":    Void,
	"XML":   Void,
	"XSRF":  Void,
	"XSS":   Void,
}

func JavaScriptReplace(s string, pattern *regexp.Regexp, fn func(match string, submatch ...string) string) string {
	idx := pattern.FindAllStringSubmatchIndex(s, -1)
	if len(idx) == 0 {
		return s
	}
	buf := &bytes.Buffer{}
	for i, v := range pattern.FindAllStringSubmatch(s, -1) {
		if i == 0 {
			buf.WriteString(s[:idx[i][0]])
		} else {
			buf.WriteString(s[idx[i-1][1]:idx[i][0]])
		}
		buf.WriteString(fn(v[0], v[1:]...))
	}
	buf.WriteString(s[idx[len(idx)-1][1]:])
	return buf.String()
}

func RegularizeName(name string) string {
	name = JavaScriptReplace(name, pattern2, func(match string, submatch ...string) string {
		n := submatch[0]
		r := submatch[1]
		if _, ok := Abbreviation[strings.ToUpper(r)]; ok {
			return n + strings.ToUpper(r)
		} else {
			return n + strings.ToUpper(r[:1]) + strings.ToLower(r[1:])
		}
	})
	name = JavaScriptReplace(name, pattern3, func(match string, submatch ...string) string {
		n := submatch[0]
		r := submatch[1]
		if _, ok := Abbreviation[n+strings.ToUpper(r)]; ok {
			return strings.ToUpper(n + r)
		} else {
			return n + r
		}
	})
	return pattern4.ReplaceAllString(name, "")
}

func NormalizeName(name string) string {
	if name == "" {
		return ""
	}
	if patternAllNumber.MatchString(name) {
		name = "Num" + name
	} else if prefix, ok := numbers[name[0]]; ok {
		name = prefix + name[1:]
	}

	name = RegularizeName(name)
	if name != "" {
		return name
	}
	return "NamingFailed"
}

func ParseNumberType(type1, type2 string) string {
	switch {
	case strings.HasPrefix(type1, "float"):
		if strings.HasPrefix(type2, "int") {
			return type1
		} else if strings.HasPrefix(type2, "float") {
			return "float64"
		}
	case strings.HasPrefix(type1, "int"):
		if strings.HasPrefix(type2, "float") {
			return type2
		} else if strings.HasPrefix(type2, "int") {
			return "int64"
		}
	}
	return "any"
}

func ParseType(t any) (rtype string, comment string) {
	switch t := t.(type) {
	case json.Delim:
		switch t {
		case '{':
			return "struct", fmt.Sprint(t)
		case '[':
			return "slice", fmt.Sprint(t)
		}
	case bool:
		if t {
			return "bool", "true"
		} else {
			return "bool", "false"
		}
	case float64:
		return "float64", strconv.FormatFloat(t, 'f', -1, 32)
	case json.Number:
		comment = t.String()
		if !strings.Contains(comment, ".") {
			i, errAtoi := strconv.Atoi(comment)
			if errAtoi == nil {
				if i >= -2147483648 && i <= 2147483647 {
					rtype = "int"
				} else {
					rtype = "int64"
				}
				return
			}
		}
		_, errParse := strconv.ParseFloat(comment, 64)
		if errParse == nil {
			rtype = "float64"
		} else {
			rtype = "json.Number"
		}
		return
	case string:
		comment = "\"" + t + "\""
		if new(time.Time).UnmarshalText([]byte(t)) == nil {
			rtype = "time.Time"
		} else {
			rtype = "string"
		}
		return
	case []any:
		return "slice", ""
	case []*object:
		return "struct", ""
	}
	return "any", ""
}

// 单个字段
type object struct {
	key     string
	rtype   string
	omit    bool
	count   int
	value   any
	comment string
}

func (o object) String() string {
	return fmt.Sprintf("%s:%s", o.key, o.rtype)
}

func (o *object) Objects() []*object {
	return o.value.([]*object)
}

func (o *object) Array() []any {
	return o.value.([]any)
}

type Converter struct {
	Any     bool
	Comment bool
	buf     *bytes.Buffer
	dec     *json.Decoder
	tab     int
}

func (c *Converter) Add(s string) {
	c.buf.WriteString(s)
}

func (c *Converter) AddTab() {
	for i := 0; i < c.tab; i++ {
		c.buf.WriteByte('\t')
	}
}

func (c *Converter) JSONToStruct(b []byte, name string) ([]byte, error) {
	name = NormalizeName(name)
	if name == "" {
		name = "AutoGenerated"
	}
	c.Add("type ")
	c.Add(name)
	c.Add(" ")
	err := c.UnmarshalJSON(bytes.ReplaceAll(b, []byte(".0"), []byte(".1")))
	if err != nil {
		return nil, err
	}
	return format.Source(c.buf.Bytes())
}

func assert(dec *json.Decoder, token json.Delim) error {
	t, err := dec.Token()
	if err != nil {
		return err
	}
	if t, ok := t.(json.Delim); !ok || t != token {
		return ErrInvalidDelim
	}
	return nil
}

func (c *Converter) UnmarshalJSON(data []byte) error {
	c.dec = json.NewDecoder(bytes.NewReader(data))
	c.dec.UseNumber()

	err := assert(c.dec, '{')
	if err != nil {
		return err
	}

	objects, err := c.ParseObject([]*object{})
	if err != nil {
		return err
	}

	_, err = c.dec.Token()
	if err != io.EOF {
		return err
	}

	c.WriteObjects(objects)

	return nil
}

func (c *Converter) ParseObject(objects []*object) ([]*object, error) {
outer:
	for c.dec.More() {
		t, err := c.dec.Token()
		if err != nil {
			return nil, err
		}

		key, ok := t.(string)
		if !ok {
			return nil, ErrInvalidToken
		}

		// 已经保存过该字段
		// 计数加 1
		// 直接读取并舍弃它的 Value
		for _, obj := range objects {
			if obj.key == key {
				obj.count++
				_, err := c.ParseValue(nil)
				if err != nil {
					return nil, err
				}
				continue outer
			}
		}

		// 获取值 并分析类型
		value, err := c.ParseValue([]*object{})
		if err != nil {
			return nil, err
		}

		rtype, comment := ParseType(value)
		if rtype == "any" && !c.Any {
			rtype = "interface{}"
		}

		if objects != nil {
			objects = append(objects, &object{
				key:     key,
				rtype:   rtype,
				count:   1,
				value:   value,
				comment: comment,
			})
		}
	}

	return objects, assert(c.dec, '}')
}

func (c *Converter) ParseValue(objects []*object) (any, error) {
	t, err := c.dec.Token()
	if err != nil {
		return nil, err
	}
	if t, ok := t.(json.Delim); ok {
		switch t {
		case '{':
			return c.ParseObject(objects)
		case '[':
			return c.ParseArray()
		}
	}
	return t, nil
}

func (c *Converter) ParseArray() (val []any, err error) {
	length := 0
	objects := make([]*object, 0)
	for c.dec.More() {
		length++
		v, err := c.ParseValue(objects)
		if err != nil {
			return nil, err
		}
		if objs, ok := v.([]*object); ok {
			objects = objs
		} else {
			val = append(val, v)
		}
	}
	err = assert(c.dec, ']')
	if err != nil {
		return
	}
	if len(val) == 0 {
		for _, obj := range objects {
			obj.omit = obj.count != length
		}
	}
	if len(objects) != 0 {
		val = append(val, objects)
	}
	return
}

func (c *Converter) WriteObjects(objects []*object) (err error) {
	c.Add("struct {\n")
	c.tab++
	for _, obj := range objects {
		c.AddTab()
		c.Add(NormalizeName(obj.key))
		c.Add(" ")

		switch obj.rtype {
		case "struct":
			err = c.WriteObjects(obj.Objects())
		case "slice":
			err = c.WriteArray(obj.Array())
		default:
			c.Add(obj.rtype)
		}
		if err != nil {
			return nil
		}

		c.Add(" `json:\"")
		c.Add(obj.key)
		if obj.omit {
			c.Add(",omitempty")
		}
		c.Add("\"`")
		if c.Comment && obj.comment != "" {
			c.Add(" // ")
			c.Add(obj.comment)
		}
		c.Add("\n")
	}
	c.tab--
	c.AddTab()
	c.Add("}")
	return nil
}

func (c *Converter) WriteArray(val []any) (err error) {
	c.Add("[]")

	// []struct
	if len(val) == 1 {
		if o, ok := val[0].([]*object); ok {
			err = c.WriteObjects(o)
			return
		}
	}

	// []xxx
	var rtype string
	for idx := 0; idx < len(val); idx++ {
		ntype, _ := ParseType(val[idx])
		if rtype == "" {
			rtype = ntype
		} else if rtype != ntype {
			rtype = ParseNumberType(ntype, rtype)
			if rtype == "any" {
				break
			}
		}
	}

	if rtype == "any" && !c.Any {
		rtype = "interface{}"
	}
	c.Add(rtype)
	return nil
}

func NewConverter(useAny bool, addComment bool) *Converter {
	return &Converter{
		Any:     useAny,
		Comment: addComment,
		buf:     &bytes.Buffer{},
	}
}
